// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { getDatabaseUrl, validateDatabaseUrl } from "./lib/env";

const databaseUrl = getDatabaseUrl();
const prismaCliUrl = databaseUrl ?? "postgresql://placeholder:placeholder@localhost:5432/placeholder";

if (databaseUrl) {
  validateDatabaseUrl(databaseUrl);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: prismaCliUrl,
  },
});
